name: Test ROSSpy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install Pip, pytest, rosspy
        run: |
          python -m pip install --upgrade pip
          pip install pywin32
          pip install pywinpty
          pip install pytest
          pip install rosspy
          pip show rosspy
      - name: Run tests
        run: python -m pytest D:\a\ROSSpy\ROSSpy\rosspy\test\test_ro.py
