name: Test ROSSpy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install packages
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install rosspy
          pip show rosspy
          pip show phreeqpy
      - name: Install IPHREEQC
        run: | 
          wget https://water.usgs.gov/water-resources/software/PHREEQC/iphreeqc-3.7.3-15968.tar.gz
          tar -xzvf iphreeqc-3.7.3-15968.tar.gz
          cd iphreeqc-3.7.3-15968
          ./configure  --prefix=/home/jovyan/iphreeqc
          make
          make check
          make install
          cp /home/jovyan/iphreeqc/iphreeqc-3.7.3-15968/src/.libs/libiphreeqc.so /srv/conda/envs/notebook/lib/python3.10/site-packages/phreeqpy/iphreeqc/libiphreeqc.so.0.0.0
      - name: Run tests
        run: python -m pytest D:\a\ROSSpy\ROSSpy\rosspy\test\test_ro.py
