name: Test ROSSpy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install IPHREEQC
        run: | 
			wget https://water.usgs.gov/water-resources/software/PHREEQC/iphreeqc-3.7.3-15968.tar.gz
			tar -xzvf iphreeqc-3.7.3-15968.tar.gz
			cd iphreeqc-3.7.3-15968
			./configure  --prefix=/home/jovyan/iphreeqc
            make
            make check
            make install 
      - name: Install packages
        run: |
          python -m pip install --upgrade pip
          pip install pywin32
          pip install pywinpty
          pip install pytest
          pip install rosspy
          pip show rosspy
      - name: Run tests
        run: python -m pytest D:\a\ROSSpy\ROSSpy\rosspy\test\test_ro.py
